name: memogenerator
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  rxdart: ^0.27.4
  provider: ^6.0.3
  google_fonts: ^3.0.1
  uuid: ^3.0.6
  json_annotation: ^4.5.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  path_provider: ^2.0.10
  screenshot: ^1.2.3
  share_plus: ^4.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  build_runner: ^2.1.11


flutter:
  uses-material-design: true
  assets:
    - assets/images/